Adding hosts file support
projectdiscovery/dnsx pull request #108
Opened 2021-09-27 16:06 UTC by Mzack9999

2021-11-01 09:16 UTC, ehsandeep requested changes
```console
$ git branch

  98-feature-custom-port-in-resolvers
* adding-hosts-file-support
  dev
  master

$ go build

$ cat /etc/hosts

# End of section
10.10.11.105 horizontall.htb
10.10.11.105 api-prod.horizontall.htb

$ echo horizontall.htb | ./dnsx -resp -hostsfile -verbose

      _             __  __
   __| | _ __   ___ \ \/ /
  / _' || '_ \ / __| \  / 
 | (_| || | | |\__ \ /  \ 
  \__,_||_| |_||___//_/\_\ v1.0.6

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
```

2021-11-01 20:48 UTC, Ice3man543 approved these changes

2021-11-08 07:28 UTC, Mzack9999 commented
@ehsandeep the domain is not shown as the resolver returns `nxdomain` (hosts file data is added to the resolver result):

```console
$ echo horizontall.htb | go run . -resp -hostsfile -verbose -rcode 0,3
horizontall.htb [NXDOMAIN]
```

Not sure if all status codes should be enabled when parsing hosts file (as above) or successful lookup should be returned for A/AAAA queries having hardcoded records in the hosts file without querying the DNS server.

2021-11-08 07:59 UTC, ehsandeep approved these changes

2021-11-08 07:59 UTC, merged